-- migrate:up

ALTER TABLE "Venue"
  ADD COLUMN description text,
  ADD COLUMN phone       text,
  ADD COLUMN website     text;

-- The target of the composite foreign key below. A plain FK on court_id alone would happily
-- accept a court belonging to a different venue than the photo claims.
ALTER TABLE "Court" ADD CONSTRAINT court_id_venue_key UNIQUE (id, venue_id);

CREATE TABLE "VenuePhoto" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id   bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  -- NULL means the photo is of the venue rather than one particular court.
  court_id   bigint,
  url        text NOT NULL,
  -- NOT NULL on purpose. A photo with no alternative text is an accessibility defect, not an
  -- optional field, and making it nullable is how it quietly becomes the norm.
  alt        text NOT NULL,
  -- There is no is_primary boolean: two rows could both claim it and the constraint needed to
  -- stop that is more machinery than ordering. The lowest sort_order is the primary photo.
  sort_order int NOT NULL DEFAULT 0,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT venue_photo_url_present CHECK (length(btrim(url)) > 0),
  CONSTRAINT venue_photo_alt_present CHECK (length(btrim(alt)) > 0),
  FOREIGN KEY (court_id, venue_id) REFERENCES "Court" (id, venue_id) ON DELETE CASCADE
);
CREATE INDEX venue_photo_venue_idx ON "VenuePhoto" (venue_id, sort_order) WHERE deleted_at IS NULL;
CREATE TRIGGER venue_photo_set_updated_at BEFORE UPDATE ON "VenuePhoto"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- migrate:down

DROP TABLE IF EXISTS "VenuePhoto";
ALTER TABLE "Court" DROP CONSTRAINT IF EXISTS court_id_venue_key;
ALTER TABLE "Venue"
  DROP COLUMN website,
  DROP COLUMN phone,
  DROP COLUMN description;
