-- migrate:up

-- A ledger, not a status column. Partial payments and refunds stay correct because there is
-- no stored state that can drift out of agreement with the sum of the rows.
CREATE TABLE "Payment" (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id   bigint REFERENCES "Booking"(id)       ON DELETE RESTRICT,
  series_id    bigint REFERENCES "BookingSeries"(id) ON DELETE RESTRICT,
  kind         payment_kind NOT NULL,
  amount_cents int NOT NULL,
  method       text NOT NULL,
  -- Staff member who took an on-site payment. Null for anything captured online.
  recorded_by  bigint REFERENCES "User"(id) ON DELETE SET NULL,
  external_ref text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payment_amount_positive CHECK (amount_cents > 0),
  -- A payment settles one occurrence or one whole series, never both and never neither.
  CONSTRAINT payment_has_one_target CHECK (num_nonnulls(booking_id, series_id) = 1)
);
CREATE INDEX payment_booking_idx ON "Payment" (booking_id);
CREATE INDEX payment_series_idx  ON "Payment" (series_id);
CREATE TRIGGER payment_set_updated_at BEFORE UPDATE ON "Payment"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE VIEW "BookingPaymentState" AS
SELECT
  b.id AS booking_id,
  b.total_cents,
  ledger.paid_cents,
  CASE
    WHEN ledger.paid_cents <= 0             THEN 'unpaid'
    WHEN ledger.paid_cents >= b.total_cents THEN 'paid'
    ELSE 'partial'
  END AS payment_state
FROM "Booking" b
CROSS JOIN LATERAL (
  SELECT COALESCE(SUM(
    CASE WHEN p.kind = 'charge' THEN p.amount_cents ELSE -p.amount_cents END
  ), 0)::int AS paid_cents
  FROM "Payment" p
  WHERE p.booking_id = b.id
) ledger;

CREATE TABLE "WaitlistEntry" (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              bigint NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  -- Either a specific court or anything at a venue. At least one is required; both is allowed
  -- and means "this court at this venue".
  venue_id             bigint REFERENCES "Venue"(id) ON DELETE CASCADE,
  court_id             bigint REFERENCES "Court"(id) ON DELETE CASCADE,
  sport                sport,
  desired              tstzrange NOT NULL,
  min_duration_minutes int NOT NULL DEFAULT 60,
  state                waitlist_state NOT NULL DEFAULT 'waiting',
  offered_at           timestamptz,
  claim_expires_at     timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT waitlist_entry_has_target CHECK (num_nonnulls(venue_id, court_id) >= 1),
  CONSTRAINT waitlist_entry_min_duration_positive CHECK (min_duration_minutes > 0),
  CONSTRAINT waitlist_entry_offer_is_complete CHECK ((offered_at IS NULL) = (claim_expires_at IS NULL))
);
-- Offers are matched by asking which waiting entries overlap a released range, so the range
-- itself is the index key.
CREATE INDEX waitlist_entry_open_idx ON "WaitlistEntry" USING gist (desired) WHERE state = 'waiting';
CREATE INDEX waitlist_entry_user_idx ON "WaitlistEntry" (user_id, state, created_at DESC);
CREATE TRIGGER waitlist_entry_set_updated_at BEFORE UPDATE ON "WaitlistEntry"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- migrate:down

DROP TABLE IF EXISTS "WaitlistEntry";
DROP VIEW IF EXISTS "BookingPaymentState";
DROP TABLE IF EXISTS "Payment";
