-- migrate:up

-- Table names are PascalCase singular and therefore quoted everywhere, matching the BYB
-- platform services. Postgres folds an unquoted identifier to lower case, so "Venue" and
-- Venue are two different names and only the quoted one exists — every reference to a table,
-- in migrations and in the repository layer alike, carries the quotes.
--
-- Column names stay snake_case. That is what the platform services predominantly use and what
-- this schema already had; the repositories rename to camelCase at the boundary.
--
-- Keys are bigint identity rather than uuid. GENERATED BY DEFAULT, not ALWAYS, because the
-- development seed assigns small fixed ids so tests can reference a row without a lookup —
-- ALWAYS would refuse those inserts without an OVERRIDING clause on every statement.

CREATE TABLE "User" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      citext NOT NULL UNIQUE,
  name       text NOT NULL,
  phone      text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER user_set_updated_at BEFORE UPDATE ON "User"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE "Venue" (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL,
  address             text NOT NULL,
  location            geography(Point, 4326) NOT NULL,
  -- IANA zone, e.g. 'Asia/Manila'. Opening hours are expressed in venue-local time, so every
  -- slot calculation needs this; a UTC offset would break the first time a zone changed rules.
  timezone            text NOT NULL,
  cancellation_window interval NOT NULL DEFAULT '24 hours',
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX venue_location_idx ON "Venue" USING gist (location);
CREATE TRIGGER venue_set_updated_at BEFORE UPDATE ON "Venue"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- A pure pairing carrying one fact (the role), so a composite PK rather than a surrogate.
CREATE TABLE "VenueMember" (
  venue_id   bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  user_id    bigint NOT NULL REFERENCES "User"(id)  ON DELETE CASCADE,
  role       venue_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (venue_id, user_id)
);
CREATE INDEX venue_member_user_idx ON "VenueMember" (user_id);
CREATE TRIGGER venue_member_set_updated_at BEFORE UPDATE ON "VenueMember"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE "Court" (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id             bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  name                 text NOT NULL,
  sport                sport NOT NULL,
  is_indoor            boolean NOT NULL DEFAULT true,
  min_duration_minutes int NOT NULL DEFAULT 60,
  max_duration_minutes int NOT NULL DEFAULT 240,
  -- Start times land on this grid; duration is still free between min and max.
  increment_minutes    int NOT NULL DEFAULT 30,
  -- Changeover time. Enforced by widening "Reservation".during, so the same exclusion
  -- constraint that prevents overlap also prevents back-to-back bookings with no gap.
  buffer_minutes       int NOT NULL DEFAULT 0,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT court_duration_range CHECK (min_duration_minutes <= max_duration_minutes),
  CONSTRAINT court_durations_positive CHECK (min_duration_minutes > 0 AND increment_minutes > 0),
  CONSTRAINT court_buffer_non_negative CHECK (buffer_minutes >= 0)
);
CREATE INDEX court_venue_sport_idx ON "Court" (venue_id, sport);
CREATE TRIGGER court_set_updated_at BEFORE UPDATE ON "Court"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- A window is an anchor weekday, a local start time, and a duration in minutes. This is the
-- only shape that expresses both a 24/7 pickleball court and a badminton court running
-- 10:00 to midnight without a special case:
--   24/7           -> one row  (0, '00:00', 10080)
--   10:00-24:00 x7 -> seven rows (n, '10:00', 840)
-- A (opens_at, closes_at) pair cannot represent either without a sentinel.
CREATE TABLE "OpeningWindow" (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id         bigint NOT NULL REFERENCES "Court"(id) ON DELETE CASCADE,
  day_of_week      smallint NOT NULL,   -- 0 = Monday, venue-local
  starts_at        time NOT NULL,
  duration_minutes int NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT opening_window_day_range CHECK (day_of_week BETWEEN 0 AND 6),
  CONSTRAINT opening_window_duration_range CHECK (duration_minutes > 0 AND duration_minutes <= 10080)
);
CREATE INDEX opening_window_court_idx ON "OpeningWindow" (court_id, day_of_week);
CREATE TRIGGER opening_window_set_updated_at BEFORE UPDATE ON "OpeningWindow"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Highest priority matching rule wins; NULL means "any". A court with no matching rule has no
-- price and cannot be quoted, which is deliberate — silence is safer than a default of zero.
CREATE TABLE "PriceRule" (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id            bigint NOT NULL REFERENCES "Court"(id) ON DELETE CASCADE,
  priority            int NOT NULL DEFAULT 0,
  day_of_week         smallint,
  starts_at           time,
  ends_at             time,
  member_only         boolean NOT NULL DEFAULT false,
  rate_per_hour_cents int NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT price_rule_day_range CHECK (day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6),
  CONSTRAINT price_rule_rate_non_negative CHECK (rate_per_hour_cents >= 0),
  CONSTRAINT price_rule_window_complete CHECK ((starts_at IS NULL) = (ends_at IS NULL))
);
CREATE INDEX price_rule_court_idx ON "PriceRule" (court_id, priority DESC);
CREATE TRIGGER price_rule_set_updated_at BEFORE UPDATE ON "PriceRule"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- migrate:down

DROP TABLE IF EXISTS "PriceRule";
DROP TABLE IF EXISTS "OpeningWindow";
DROP TABLE IF EXISTS "Court";
DROP TABLE IF EXISTS "VenueMember";
DROP TABLE IF EXISTS "Venue";
DROP TABLE IF EXISTS "User";
