-- migrate:up

-- A rating with nothing behind it is just a number a stranger typed. `booking_id UNIQUE` is the
-- whole integrity story: a review must point at a booking, so only somebody who actually booked
-- can leave one, and they can leave exactly one per booking. The service adds the other two
-- conditions it cannot express here — the booking belongs to the caller, and play has ended.
--
-- `venue_id` and `user_id` are derivable from the booking and are stored anyway, deliberately:
-- every read of this table filters or groups by venue, and the alternative is a join to
-- "Booking" on the hot path of both the search sort and the venue page.
CREATE TABLE "Review" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL UNIQUE REFERENCES "Booking"(id) ON DELETE CASCADE,
  venue_id   bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  user_id    bigint NOT NULL REFERENCES "User"(id)  ON DELETE CASCADE,
  rating     smallint NOT NULL,
  -- Optional. A star with no words is a real opinion, and demanding prose to accompany it is
  -- how a rating system collects fewer, angrier reviews.
  body       text,
  -- Soft delete, repo-wide. A withdrawn review stops counting towards the average but the row
  -- survives, because "this venue was rated 2 while you were booking" is the fact in dispute
  -- if anyone ever asks.
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT review_rating_range CHECK (rating BETWEEN 1 AND 5),
  -- An empty string is not "no comment", it is a body that renders as a blank paragraph.
  CONSTRAINT review_body_not_blank CHECK (body IS NULL OR length(btrim(body)) > 0)
);

-- The venue page reads newest-first and the aggregate groups by venue; both are this index.
CREATE INDEX review_venue_idx ON "Review" (venue_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX review_user_idx ON "Review" (user_id, created_at DESC);

CREATE TRIGGER review_set_updated_at BEFORE UPDATE ON "Review"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- A view rather than columns on "Venue", matching "BookingPaymentState": an aggregate that is
-- computed cannot drift out of agreement with the rows it aggregates, and there is no write
-- path that can forget to update it.
--
-- LEFT JOIN so every venue appears. A venue with no reviews gets review_count 0 and a NULL
-- average — not zero, which would sort it below a genuinely bad venue and read as a rating of
-- none out of five.
CREATE VIEW "VenueRating" AS
SELECT v.id AS venue_id,
       count(r.id)::int AS review_count,
       round(avg(r.rating), 2) AS rating_avg
FROM "Venue" v
LEFT JOIN "Review" r ON r.venue_id = v.id AND r.deleted_at IS NULL
GROUP BY v.id;

-- migrate:down

DROP VIEW IF EXISTS "VenueRating";
DROP TABLE IF EXISTS "Review";
