-- Courte v1 schema
-- See docs/adr/ for the reasoning behind the availability model, the overlap
-- constraint, and the module boundaries.
--
-- Two conventions, applied everywhere and adopted from the BYB platform services:
--   * Table names are PascalCase singular, and therefore ALWAYS double-quoted. Postgres folds
--     an unquoted identifier to lower case, so `FROM Court` silently becomes `court` and fails.
--     Column names stay snake_case; repositories rename to camelCase at the boundary.
--   * Keys are bigint identity, not uuid. GENERATED BY DEFAULT rather than ALWAYS, so the
--     development seed can assign small fixed ids that tests reference without a lookup.
--
-- Index and constraint names follow the singular table name and are not quoted, because they
-- are lower case already.

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- required for court_id WITH = in the exclusion constraint
CREATE EXTENSION IF NOT EXISTS postgis;      -- venue proximity search
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE sport             AS ENUM ('pickleball','badminton','basketball','volleyball','tennis','futsal');
CREATE TYPE court_surface     AS ENUM ('indoor','outdoor','covered');
CREATE TYPE booking_status    AS ENUM ('pending','confirmed','cancelled','completed','no_show');
CREATE TYPE booking_source    AS ENUM ('online','phone','walk_in');
CREATE TYPE reservation_kind  AS ENUM ('booking','hold','blackout');
CREATE TYPE reservation_state AS ENUM ('active','released');
CREATE TYPE payment_kind      AS ENUM ('charge','refund');
CREATE TYPE waitlist_state    AS ENUM ('waiting','offered','claimed','expired','cancelled');

-- ---------------------------------------------------------------- identity

CREATE TABLE "User" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      citext NOT NULL UNIQUE,
  name       text NOT NULL,
  phone      text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- --------------------------------------------------------------- inventory

-- `deleted_at` is the archive marker, repo-wide: NULL is live, a timestamp is retired.
-- Nothing in the inventory is ever hard-deleted — reservations cascade from courts, so a real
-- DELETE would take paid bookings' slots with it. Filtered at discovery, not at lookup; see
-- the soft-delete section of CONVENTIONS.md.
CREATE TABLE "Venue" (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL,
  address             text NOT NULL,
  location            geography(Point, 4326) NOT NULL,
  timezone            text NOT NULL,                        -- IANA, e.g. 'Asia/Manila'
  cancellation_window interval NOT NULL DEFAULT '24 hours',
  description         text,                                 -- owner-written; null for most venues
  phone               text,
  website             text,
  deleted_at          timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX venue_location_idx ON "Venue" USING gist (location) WHERE deleted_at IS NULL;

CREATE TABLE "VenueMember" (
  venue_id bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  user_id  bigint NOT NULL REFERENCES "User"(id)  ON DELETE CASCADE,
  role     text NOT NULL CHECK (role IN ('owner','staff')),
  PRIMARY KEY (venue_id, user_id)
);

CREATE TABLE "Court" (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id             bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  name                 text NOT NULL,
  sport                sport NOT NULL,
  surface              court_surface NOT NULL,               -- covered is roofed but open-sided
  min_duration_minutes int NOT NULL DEFAULT 60,
  max_duration_minutes int NOT NULL DEFAULT 240,
  increment_minutes    int NOT NULL DEFAULT 30,
  buffer_minutes       int NOT NULL DEFAULT 0,               -- changeover, enforced via "Reservation".during
  deleted_at           timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CHECK (min_duration_minutes <= max_duration_minutes),
  UNIQUE (id, venue_id)                                      -- target of "VenuePhoto"'s composite FK
);
CREATE INDEX court_live_venue_idx ON "Court" (venue_id, sport) WHERE deleted_at IS NULL;

-- No is_primary flag: two rows could both claim it. The lowest sort_order is the primary photo.
-- `alt` is NOT NULL because a photo with no alternative text is a defect, not an option.
CREATE TABLE "VenuePhoto" (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id   bigint NOT NULL REFERENCES "Venue"(id) ON DELETE CASCADE,
  court_id   bigint,                                           -- null = a photo of the venue itself
  url        text NOT NULL,
  alt        text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (court_id, venue_id) REFERENCES "Court" (id, venue_id) ON DELETE CASCADE
);
CREATE INDEX venue_photo_venue_idx ON "VenuePhoto" (venue_id, sort_order) WHERE deleted_at IS NULL;

-- A lookup table, not an enum: a new amenity should be a row, not a migration. The slug is the
-- natural key because it travels in `?amenities=parking,showers`.
CREATE TABLE "Amenity" (
  slug       text PRIMARY KEY CHECK (slug ~ '^[a-z][a-z0-9_]*$'),
  label      text NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Writers revive rather than insert, or re-ticking an amenity is a PK violation:
--   ON CONFLICT (venue_id, amenity_slug) DO UPDATE SET deleted_at = NULL
CREATE TABLE "VenueAmenity" (
  venue_id     bigint NOT NULL REFERENCES "Venue"(id)      ON DELETE CASCADE,
  amenity_slug text NOT NULL REFERENCES "Amenity"(slug) ON DELETE RESTRICT,
  deleted_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (venue_id, amenity_slug)
);
CREATE INDEX venue_amenity_slug_idx ON "VenueAmenity" (amenity_slug) WHERE deleted_at IS NULL;

-- A window is an anchor weekday, a local start time, and a duration. This is the
-- only shape that handles both a 24/7 pickleball court and a badminton court open
-- 10:00 to midnight without a special case.
--   24/7            -> one row: (0, '00:00', 10080)
--   10:00-24:00 x7  -> seven rows: (n, '10:00', 840)
CREATE TABLE "OpeningWindow" (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id         bigint NOT NULL REFERENCES "Court"(id) ON DELETE CASCADE,
  day_of_week      smallint NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),   -- 0 = Monday, venue-local
  starts_at        time NOT NULL,
  duration_minutes int NOT NULL CHECK (duration_minutes > 0 AND duration_minutes <= 10080)
);
CREATE INDEX opening_window_court_idx ON "OpeningWindow" (court_id, day_of_week);

-- Highest priority matching rule wins; NULL means "any". valid_from/valid_to scope a rule to
-- calendar dates — a holiday, a promotion, or a price rise — and are compared in venue-local
-- time. Two rules that match the same moment at the same priority are refused on save.
CREATE TABLE "PriceRule" (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id            bigint NOT NULL REFERENCES "Court"(id) ON DELETE CASCADE,
  priority            int NOT NULL DEFAULT 0,
  day_of_week         smallint CHECK (day_of_week BETWEEN 0 AND 6),
  starts_at           time,
  ends_at             time,
  valid_from          date,                    -- inclusive; null is unbounded in that direction
  valid_to            date,
  member_only         boolean NOT NULL DEFAULT false,
  rate_per_hour_cents int NOT NULL CHECK (rate_per_hour_cents >= 0),
  CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from),
  -- An overnight window is not supported anywhere in the stack; two rules express one.
  CHECK (starts_at IS NULL OR ends_at > starts_at)
);
-- The secondary ordering is load-bearing: without it two equal-priority rules resolve in
-- whatever order Postgres felt like, and a court could quote differently between two
-- identical requests.
CREATE INDEX price_rule_court_idx ON "PriceRule" (court_id, priority DESC, created_at DESC, id);

-- ------------------------------------------------------------------ intent

CREATE TABLE "BookingSeries" (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by         bigint NOT NULL REFERENCES "User"(id),
  rrule              text NOT NULL,          -- RFC 5545
  timezone           text NOT NULL,          -- recurrence expands in this zone, not UTC
  dtstart            timestamptz NOT NULL,
  materialised_until timestamptz NOT NULL,   -- rolling horizon; extended by a job
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "Booking" (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id        bigint REFERENCES "BookingSeries"(id) ON DELETE SET NULL,
  occurrence_start timestamptz,              -- originally scheduled start; survives a moved occurrence
  user_id          bigint NOT NULL REFERENCES "User"(id),
  venue_id         bigint NOT NULL REFERENCES "Venue"(id),
  status           booking_status NOT NULL DEFAULT 'pending',
  source           booking_source NOT NULL DEFAULT 'online',
  total_cents      int NOT NULL CHECK (total_cents >= 0),
  rate_snapshot    jsonb NOT NULL,           -- rules resolved at quote time; never recomputed
  cancelled_at     timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT occurrence_requires_series CHECK ((series_id IS NULL) = (occurrence_start IS NULL))
);
CREATE UNIQUE INDEX booking_series_occurrence_idx
  ON "Booking" (series_id, occurrence_start) WHERE series_id IS NOT NULL;
CREATE INDEX booking_user_idx  ON "Booking" (user_id, created_at DESC);
CREATE INDEX booking_venue_idx ON "Booking" (venue_id, status);

-- --------------------------------------------------------------- the guard

-- One booking owns many reservations, which is what makes a tournament across six
-- courts a single atomic insert: if any row overlaps, the whole booking aborts.
CREATE TABLE "Reservation" (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id    bigint NOT NULL REFERENCES "Court"(id) ON DELETE CASCADE,
  booking_id  bigint REFERENCES "Booking"(id) ON DELETE CASCADE,
  kind        reservation_kind NOT NULL,
  state       reservation_state NOT NULL DEFAULT 'active',
  during      tstzrange NOT NULL,            -- blocked interval, includes changeover buffer
  play_during tstzrange NOT NULL,            -- what the player actually gets, shown in the UI
  expires_at  timestamptz,                   -- holds only
  reason      text,                          -- blackouts only
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_ref_matches_kind CHECK (
    (kind =  'blackout' AND booking_id IS NULL) OR
    (kind <> 'blackout' AND booking_id IS NOT NULL)
  ),
  CONSTRAINT hold_has_expiry CHECK ((kind = 'hold') = (expires_at IS NOT NULL)),
  CONSTRAINT during_is_bounded CHECK (lower(during) IS NOT NULL AND upper(during) IS NOT NULL),
  CONSTRAINT play_within_during CHECK (during @> play_during)
);

-- The whole product rests on this.
ALTER TABLE "Reservation"
  ADD CONSTRAINT reservation_no_overlap
  EXCLUDE USING gist (court_id WITH =, during WITH &&)
  WHERE (state = 'active');

CREATE INDEX reservation_court_during_idx ON "Reservation" USING gist (court_id, during);
CREATE INDEX reservation_expiry_idx       ON "Reservation" (expires_at)
  WHERE kind = 'hold' AND state = 'active';

-- ---------------------------------------------------------------- payments

-- A ledger, not a status column. Partial payments and refunds stay correct because
-- nothing is stored that can disagree with the sum.
CREATE TABLE "Payment" (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id   bigint REFERENCES "Booking"(id)       ON DELETE RESTRICT,
  series_id    bigint REFERENCES "BookingSeries"(id) ON DELETE RESTRICT,
  kind         payment_kind NOT NULL,
  amount_cents int NOT NULL CHECK (amount_cents > 0),
  method       text NOT NULL,                     -- 'cash','gcash','maya','card'
  recorded_by  bigint REFERENCES "User"(id),         -- staff member, for on-site payments
  external_ref text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payment_has_one_target CHECK (num_nonnulls(booking_id, series_id) = 1)
);
CREATE INDEX payment_booking_idx ON "Payment" (booking_id);

CREATE VIEW "BookingPaymentState" AS
SELECT
  b.id AS booking_id,
  b.total_cents,
  led.paid_cents,
  CASE
    WHEN led.paid_cents <= 0             THEN 'unpaid'
    WHEN led.paid_cents >= b.total_cents THEN 'paid'
    ELSE 'partial'
  END AS payment_state
FROM "Booking" b
CROSS JOIN LATERAL (
  SELECT COALESCE(SUM(
    CASE WHEN p.kind = 'charge' THEN p.amount_cents ELSE -p.amount_cents END
  ), 0)::int AS paid_cents
  FROM "Payment" p
  WHERE p.booking_id = b.id
) led;

-- ---------------------------------------------------------------- waitlist

CREATE TABLE "WaitlistEntry" (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              bigint NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  venue_id             bigint REFERENCES "Venue"(id) ON DELETE CASCADE,
  court_id             bigint REFERENCES "Court"(id) ON DELETE CASCADE,
  sport                sport,
  desired              tstzrange NOT NULL,
  min_duration_minutes int NOT NULL DEFAULT 60,
  state                waitlist_state NOT NULL DEFAULT 'waiting',
  offered_at           timestamptz,
  claim_expires_at     timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT waitlist_has_target CHECK (num_nonnulls(venue_id, court_id) >= 1)
);
CREATE INDEX waitlist_entry_open_idx ON "WaitlistEntry" USING gist (desired) WHERE state = 'waiting';
CREATE INDEX waitlist_entry_user_idx ON "WaitlistEntry" (user_id, state);
